<?php

/**
 * Template Name: Single
 *
 * @package WordPress
 */

get_header();

?>
    <main class="woowContentFull main main_single">
        <div class="woowContent1400">
            <div class="main_single_content">
                <div class="single_img">
                    <img src="<?=IMGURL?>blog/blog_1.jpeg" alt="">
                </div> 
                <div class="single_info">
                    <h1>ES DIVERTIDO SER KINKY (IT IS FUN TO BE KINKY)</h1>
                    <p class="single_breadcumps"><a href="">Deja un comentario / Línea BDSM / Por Admin Dale+</a></p>
                    <div class="single_info_description">
                        <h2>Una noche fría como cualquiera en Bogotá, no podría evitar que disfrutara de la más sorprendente experiencia <em>underground</em>, que nunca había vivido.</h2>
                        <p>Nadie pensaría que un sábado común y corriente Chapigay, en medio de una pandemia y teniendo que utilizar tapabocas incluso en los bares, no sería excusable para adentrarme en el divertido mundo Kinky a través de las puertas de una de las mejores marcas y con gran recordación por parte de la comunidad fetish del país.&nbsp; El evento era la inauguración de la nueva tienda Dale Más.</p>
                        <p><em><strong><a href="https://dalemas.store/" target="_blank" rel="noopener noreferrer">Ubicado en pleno corazón de la rumba gay de la ciudad de Bogotá, en plena Calle 59 # 9 – 30</a>, se ponía al descubierto mediante las rigurosas reglas de bioseguridad, un imponente local de fachada negra, en cuya vitrina exponen la imagen de los modelos de <a href="https://dalemas.store/" target="_blank" rel="noopener noreferrer">Dale +</a>, mirando como para invitar al pecado.</strong></em></p>
                        <p>En la puerta, un hombre robusto, musculoso, con unos pantalones muy bien ajustados y marcando justo ahí, donde la mirada no deja de desviarse, confirma la lista de invitados, brindando gel antibacterial en las manos.&nbsp; Yo a punto de desviar mis pensamientos imaginando que puede llegar a ser otro tipo de líquido viscoso el que coloco en mis manos.</p>
                        <p>Al entrar, te sientes como en una auténtica tienda fetichista de Ámsterdam, solo que adicionalmente, te encuentras con unos hombres esculturalmente bellos como los hay en Colombia, y con ese calor humano que cualquier colombiano sabe albergar.</p>
                        <p>Me sigue con la mirada un hombre de más o menos 1,65 cm de estatura, mi misma estatura, con unos ojos tan claros como el agua del mar, pero con un cuerpo que se vería muy bien con unas cuantas cuerdas amarrado a él.&nbsp; Pero para qué hablar de su cuerpo, si sus ojos siguen hipnotizándome, a pesar que, a causa del tapabocas, es lo único que puedo apreciarle.&nbsp; Su voz con acento paisa no deja que le pierda cada sonido que emana de aquel hombrecito de bellos ojos azules.&nbsp; Me saluda y me comenta que él es el administrador de la tienda en Medellín y que vino aquí porque está encantado con la marca, la empresa lo quiere mucho y él celebra cada avance que da.</p>
                        <p>Me habla sobre lo importante que fue para <a href="https://dalemas.store/" target="_blank" rel="noopener noreferrer">Dayner, el fundador de Dale +</a>, pasar 20 años en Holanda y adentrarse en el mundo y la cultura leather y BDSM, para, tiempo después, regresar con su pareja a Colombia y levantar un sueño al que le ha ido bastante bien, en parte por la excelente calidad y dedicación que ha puesto a cada prenda, a cada material y en cada colección que Dale + ha construido durante estos más de 2 años en el mercado.</p>
                        <p>Él sigue mostrándome todo lo que la nueva tienda de Dale Más tiene para ofrecer al público amante del leather, BDSM, fetichistas en general y aquellos más osados.</p>
                        <p>Su más reciente colección está plagada de cuero negro y prendas que se podría usar en una frenética faena, así como en una cena con amigos o simplemente para estar en casa. Su calidad y comodidad en sus materias primas atraen hasta el ojo más conservador, pero al más picante también.</p>
                        <p>Me despido de ojos bonitos, para darle una vuelta a la tienda.&nbsp; Me encuentro entonces con un desfile de dominatrices, masters y sumisos que, a pesar de algunos tener los suficientes músculos para derribar una puerta, son felices complaciendo a sus amos que discuten y ríen con seguramente amigos y conocidos en la tienda, la que esa noche servía como punto de encuentro para esta comunidad que ha venido cobrando más relevancia no sólo en Bogotá, sino en todo el país.</p>
                        <p>Aquella era una fiesta. En el extremo de la tienda, alcanzo a ver a <a href="https://www.instagram.com/yetow_ytw/" target="_blank" rel="noopener noreferrer">Yetow</a> creador de <a href="https://www.instagram.com/mundo_subterraneo_ytw/" target="_blank" rel="noopener noreferrer">Mundo Subterráneo</a>, reconocido Master y toda una celebridad en el tema de BDSM a nivel nacional; practicándole Bondage a un conejito de antifaz negro, quizás muy travieso, el cual necesitaba ser castigado, bueno, lo digo porque aquel conejito se le ha ocurrido pasearse por la tienda con tan solo unas medias largas hasta la rodilla y un diminuto brief, ambos rojos, ambos de la marca anfitriona.&nbsp; Muy danzante el conejito aquel con la maravillosa música del <a href="https://www.instagram.com/juanreina.r/" target="_blank" rel="noopener noreferrer">DJ Juan Reina</a> que amenizo durante toda la noche.</p>
                        <p>Me quedo fascinado viendo tal escena. Al girar a mi derecha me encuentro con quizás el tesoro de la madriguera de aquel conejo, una pared con todos los accesorios que solo una tienda fetichista como Dale más podría brindar.&nbsp; Una pared que comparada a Anastasia Steele, sería como los accesorios de Barbie, una Barbie muy traviesa.&nbsp; Y yo en frente de esa pared, como un dulce niño mirando la vitrina de una muy colorida dulcería.</p>
                        <p>En ese momento veo atravesar la entrada en unas botas altas, rojas, al mejor estilo de <a href="https://egocitymgz.com/10-peliculas-que-te-hincharan-de-orgullo/" target="_blank" rel="noopener noreferrer">Kinky boots</a>, con unos tacones tan altos que te da vértigo de solo mirar hacia abajo, con una belleza de otro plantea, a su majestad <a href="https://www.instagram.com/venusjoficial/" target="_blank" rel="noopener noreferrer">la Reina Venus</a>. Con unos rasgos fuertes y un rostro casi inexpresivo, pero con una amabilidad que siempre la caracteriza, llega a castigar a aquel conejito malo y a <a href="https://www.instagram.com/ramvidzapata/" target="_blank" rel="noopener noreferrer">Ramvid</a>, modelo e influenciador venezolano radicado en Bogotá, quien toda la noche exhibe su rimbombante nalgatorio con prendas de la marca.</p>
                        <p>Ojos azules llega para tocarme la espalda, mis rodillas casi me fallan al escucharlo dirigirse a mí. &nbsp;Nos invita a salir de la tienda, ya que estábamos cumpliendo el aforo permitido por la Secretaría de Salud, pero también, para continuar la fiesta en la cera de la tienda.&nbsp; Al salir, veo como una damisela de dulces coletas y vestida de brillos y lentejuelas, enciende literalmente la noche.&nbsp; Con sus bastones, su aliento, sus malabares de fuego y unas piernas tan elásticas que bien podrían ahorcar a cualquiera allí presente. La mayoría de los hombres en el lugar, semidesnudos con abdómenes de acero, perfectos para lavar esos <a href="https://dalemas.store/" target="_blank" rel="noopener noreferrer">JOCK HORNY,</a> que vi en el vestíbulo de la tienda y aún estoy tentado a comprar.</p>
                        <p>Uno de esos lavaderos esculturales lo posee el actor porno <a href="https://www.instagram.com/leogalileo7/" target="_blank" rel="noopener noreferrer">Leo Galileo</a>; y cuál fue mi sorpresa al verlo ahí, en la tienda, sonriéndome, aunque creo que le sonreía a todo el mundo, me saluda, me pregunta cómo me llamo y yo entro en éxtasis al oír mi nombre salir de sus labios.&nbsp; Le pido que me permita tomarme una foto y el mismo agarra mi celular, yo queriendo decirle que agarrara lo que quisiera, pero mi profesionalismo me obliga a mantener mi compostura, aunque esa noche, ese lugar invitaba a no tenerla.</p>
                        <p>Después de despedirme de Leo, una mujer alta, con bozal de cuero, llega exhibiendo a su mascota, un hermoso canino bastardo, un hombre que con su <a href="https://dalemas.store/" target="_blank" rel="noopener noreferrer">máscara de <em>Dog Play</em></a> exhibe un culo tonificado, siendo castigado por ella, pero bailando feliz al ser azotado delante de todos nosotros.</p>
                        <p>Las sorpresas siguen llegando aquella noche a <a href="https://dalemas.store/" target="_blank" rel="noopener noreferrer">Dale +</a>, la mía, al ver al actor de porno amateur <a href="https://www.instagram.com/leninyulian/" target="_blank" rel="noopener noreferrer">Lenin Yulian Montenegro</a>, más conocido como Mr. Anaconda, cuyos 25 centímetros de profesionalismo le hacen valer su título nobiliario; bebiendo y celebrando como un asistente más.</p>
                        <h4><strong>Aquella noche pude darme cuenta que ningún fetiche es raro, que todos los cuerpos, en todas sus formas pueden ser deseados y que, en una sola noche, uno puede encontrar más de una historia para ser relatada y vivida.</strong></h4>
                        <p>Sé que volveré a aquella tienda que de seguro muchos consideraran su hogar, su refugio, su confidente.&nbsp; Yo lo haré porque cada artículo, cada prenda, de excelente calidad y diseños maravillosos, no solo están diseñados para el disfrute del sexo en la forma que se desee, los considero también dignos de usarlos y exhibirlos en la cotidianidad, en el día a día, son realmente hermosos. También lo haré para reencontrarme con aquella pared, con mi vitrina de golosinas, ya que me atrajeron aquellos dulces, y aquella pared me hace pensar en mi lado divertido.</p>
                        <p><strong>Escrito por:</strong></p>
                        <p><a href="https://ivanfelipebr.wordpress.com/sobre-mi/" target="_blank" rel="noopener noreferrer">Iván Felipe Bohórquez.</a><br> <a href="https://ivanfelipebr.wordpress.com/" target="_blank" rel="noopener noreferrer">https://ivanfelipebr.wordpress.com/</a><br> Twitter: <a href="https://twitter.com/@pipe_on/" target="_blank" rel="noopener noreferrer">@pipe_on</a><br> Facebook: <a href="https://www.facebook.com/ivanfelipebr" target="_blank" rel="noopener noreferrer">/IvanFelipeBR</a><br> Instagram: <a href="https://www.instagram.com/ivanfelipebr/" target="_blank" rel="noopener noreferrer">@ivanfelipebr</a><br> <a href="https://www.linkedin.com/in/ivan-felipe-bohorquez-ramirez/" target="_blank" rel="noopener noreferrer">LinkedIn: Iván Felipe Bohórquez</a></p>
                    </div>
                </div>     
            </div>
        </div>
    </main>
<?php
get_footer();
?>